"""changed name to username

Revision ID: 357b0a8a68e1
Revises: a6fd96f7d12f
Create Date: 2023-12-11 11:44:57.873359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357b0a8a68e1'
down_revision = 'a6fd96f7d12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
